ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS inn VARCHAR(20),
  ADD COLUMN IF NOT EXISTS kpp VARCHAR(20),
  ADD COLUMN IF NOT EXISTS ogrn VARCHAR(20),
  ADD COLUMN IF NOT EXISTS legal_address VARCHAR(500),
  ADD COLUMN IF NOT EXISTS bank_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bank_account VARCHAR(34),
  ADD COLUMN IF NOT EXISTS bank_bik VARCHAR(20),
  ADD COLUMN IF NOT EXISTS bank_corr_account VARCHAR(34),
  ADD COLUMN IF NOT EXISTS signer_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS signer_position VARCHAR(255);