ALTER TABLE leads ADD COLUMN IF NOT EXISTS consent_at TIMESTAMP NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS consent_ip VARCHAR(45) NULL;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS consent_text TEXT NULL;